version: '3'
services:
  foundryvtt:
    image: direckthit/fvtt-docker:latest
    container_name: toril22-fvtt
    ports: 
      - 30000:30000
    volumes:
      - ./volumes/host:/host
      - ./volumes/data:/data/foundryvtt
      - ./volumes/app:/opt/foundryvtt/resources/app
    restart: unless-stopped
